runtime: nodejs18

env_variables:
  DISCORD_BOT_TOKEN: MTA2MDgwNzk0Mzk2NjE3MTE0Ng.GByBMN.TaeQbPeTmo7dtU1pTU6Q6sd54Gl1w8iYXn4qVs
  DISCORD_CLIENT_ID: 1060807943966171146
  OPENAI_TOKEN_KEY: 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
  API_REVERSE_PROXY_SERVER: https://chat.duti.tech/api/conversation
  ENABLE_DIRECT_MESSAGES: false
  CONVERSATION_MEMORY_SECONDS: 300
  CONVERSATION_START_PROMPT: false
  USE_EMBED: true
  MODE_OPENAI_AUTH: token