runtime: nodejs18

env_variables:
  DISCORD_BOT_TOKEN: MTA2MDgwNzk0Mzk2NjE3MTE0Ng.GoZ7Pz.SNgkOESSsfDjo0Asv2UKUhJ53PZYHrJ2jXtUsw
  DISCORD_CLIENT_ID: 1060807943966171146
  OPENAI_TOKEN_KEY: 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
  API_REVERSE_PROXY_SERVER: https://chat.duti.tech/api/conversation
  ENABLE_DIRECT_MESSAGES: false
  CONVERSATION_MEMORY_SECONDS: 300
  CONVERSATION_START_PROMPT: false
  USE_EMBED: true
  MODE_OPENAI_AUTH: token